In [1]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

In [2]:
type(arr1)

numpy.ndarray

In [4]:
arr1.shape

(5,)

In [5]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(5, 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [6]:
arr3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr3.shape

(2, 4)

In [7]:
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
arr4 = np.ones((2, 3))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
arr5 = np.eye(3)
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
arr5.ndim

2

In [12]:
arr5.size

9

In [13]:
arr5.dtype

dtype('float64')

In [14]:
arr5.itemsize

8

In [15]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

#Element-wise addition
print(arr1 + arr2)

[11 22 33 44 55]


In [16]:
#Element-wise subtraction
print(arr2 - arr1)

[ 9 18 27 36 45]


In [17]:
#Element-wise multiplication
print(arr1 * arr2)

#Element-wise division
print(arr2 / arr1)

[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [18]:
print(np.sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [19]:
print(np.exp(arr1))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [20]:
print(np.sin(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [21]:
print(np.log(arr1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [22]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array:\n", arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
print(arr[0][1])

2


In [24]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [29]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [30]:
arr[0][0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [31]:
#Normalization 
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [32]:
np.median(data)

3.0

In [33]:
np.var(data)

2.0

In [34]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[data > 5]

array([ 6,  7,  8,  9, 10])